# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' The algorithm of Coordinate Descent for LASSO
#' @param X the observation vector
#' @param y the response vector 
#' @param lambda the smoothing parameter
#' @return the list which concludes the estimator beta, 
#' the corresponding values of objective functions and 
#' the numbers of iteration 
#' @examples
#' require(zhouyahomework1)
#' # Generate Data
#' n = 100
#' p = 500
#' sigma_noise = 0.5
#' beta = rep(0, p)
#' beta[1:6] = c(5,10,3,80,90,10)
#' XData = matrix(rnorm(n*p,sd=10), nrow = n, ncol=p)
#' X=XData
#' for (i in 1:500){
#' X[,i]=((X[,i]-sum(X[,i])/n))/((var(X[,i])*99/100)^0.5)
#' }
#' YData = X %*% beta + rnorm(n, sd = sigma_noise)
#' YData=YData-sum(YData)/100
#' XData=X
#' #Coordinate Descent for LASSO
#' betaHat1list = CoordinateDescent(XData,YData,1)
#' betaHat1=unlist(betaHat1list["betahat"])
CoordinateDescent <- function(X, y, lambda) {
    .Call('_zhouyahomework1_CoordinateDescent', PACKAGE = 'zhouyahomework1', X, y, lambda)
}

#' The algorithm of Proximal Operator for LASSO
#' @param X the observation vector
#' @param y the response vector 
#' @param lambda the smoothing parameter
#' @return the list which concludes the estimator beta, 
#' the corresponding values of objective functions and 
#' the numbers of iteration 
#' @examples
#' require(zhouyahomework1)
#' # Generate Data
#' n = 100
#' p = 500
#' sigma_noise = 0.5
#' beta = rep(0, p)
#' beta[1:6] = c(5,10,3,80,90,10)
#' XData = matrix(rnorm(n*p,sd=10), nrow = n, ncol=p)
#' X=XData
#' for (i in 1:500){
#' X[,i]=((X[,i]-sum(X[,i])/n))/((var(X[,i])*99/100)^0.5)
#' }
#' YData = X %*% beta + rnorm(n, sd = sigma_noise)
#' YData=YData-sum(YData)/100
#' XData=X
#' # Proximal Operator for LASSO
#' betaHat2list=ProximalOperator(YData, XData, 1)
#' betaHat2 = unlist(betaHat2list["betahat"])
ProximalOperator <- function(X, y, lambda) {
    .Call('_zhouyahomework1_ProximalOperator', PACKAGE = 'zhouyahomework1', X, y, lambda)
}

